spring:
  application:
    name: hhplus
  profiles:
    active: local
  datasource:
    name: HangHaePlusDataSource
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 3
      connection-timeout: 10000
      max-lifetime: 60000
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: false
#    hibernate:
#      ddl-auto: create
    properties:
      hibernate.timezone.default_storage: NORMALIZE_UTC
      hibernate.jdbc.time_zone: UTC

---
#spring.config.activate.on-profile: local, test
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/hhplus?characterEncoding=UTF-8&serverTimezone=UTC
#    username: application
#    password: application

---

spring.config.activate.on-profile: local

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hhplus?characterEncoding=UTF-8&serverTimezone=UTC
    username: application
    password: application
  jpa:
    hibernate:
      ddl-auto: validate

---

spring.config.activate.on-profile: test

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb  # @DynamicPropertySource로 override
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: create